---
- name: Works
  hosts: Alt
  gather_facts: yes
  tasks:
    - name: Hostname
      set_fact:
        pc_name: "{{ ansible_hostname }}"
    - name: IPs
      set_fact:
        pc_ip: "{{ ansible_default_ipv4.address }}"
    - name: Save Info
      copy:
        dest: "/etc/ansible/PC_INFO/{{ pc_name }}.yml"
        content:
          hostname: “{{ pc_name }}”
          ip_address: “{{ pc_ip }}”
        mode: '0644'
      delegate_to: localhost
