---
- name: Works
  hosts: Alt
  gather_facts: yes
  tasks:
    - name: Create info
      delegate_to: localhost
      copy:
        dest: "/etc/ansible/PC_INFO/{{ ansible_hostname }}.yml"
        content: |
            Имя компьютера: '{{ ansible_hostname }}'
            IP-адрес компьютера: '{{ ansible_default_ipv4.address }}'
            
